// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class CTDadosValidosTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void cTDadosValidos() {
        //Acessar a página mantis
    driver.Navigate().GoToUrl("https://mantis-prova.base2.com.br/login_page.php");
        //visão da página
    driver.Manage().Window.Size = new System.Drawing.Size(665, 722);
        //clique em username
    driver.FindElement(By.Name("username")).Click();
        //digitar o username
    driver.FindElement(By.Name("username")).SendKeys("tiago.soares");
        //digitar a senha
    driver.FindElement(By.Name("password")).SendKeys("98554211");
        //clique em login
    driver.FindElement(By.CssSelector(".button")).Click();
    try {
      Thread.Sleep(7000);
    } catch {
      Console.WriteLine("{0} Exception caught.", e);
    }
        //validando o usuario logado
    Assert.That(driver.FindElement(By.CssSelector(".login-info-left")).Text, Is.EqualTo("Logged in as: tiago.soares (Tiago Soares - reporter)"));
        //clique em logout
    driver.FindElement(By.LinkText("Logout")).Click();
  }
}
