// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class CTmudaridiomaTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void cTmudaridioma() {
    driver.Navigate().GoToUrl("https://mantis-prova.base2.com.br/my_view_page.php");
    driver.Manage().Window.Size = new System.Drawing.Size(665, 723);
    driver.FindElement(By.Name("username")).Click();
    driver.FindElement(By.Name("username")).SendKeys("tiago.soares");
    driver.FindElement(By.Name("password")).Click();
    driver.FindElement(By.Name("password")).SendKeys("98554211");
    driver.FindElement(By.CssSelector(".button")).Click();
    driver.FindElement(By.LinkText("My Account")).Click();
    driver.FindElement(By.LinkText("Preferences")).Click();
    driver.FindElement(By.Name("language")).Click();
    {
      var dropdown = driver.FindElement(By.Name("language"));
      dropdown.FindElement(By.XPath("//option[. = 'portuguese_brazil']")).Click();
    }
    driver.FindElement(By.CssSelector("select > option:nth-child(37)")).Click();
    driver.FindElement(By.CssSelector(".button:nth-child(1)")).Click();
    driver.FindElement(By.CssSelector("body > div img")).Click();
    driver.FindElement(By.LinkText("Minha Conta")).Click();
    driver.FindElement(By.LinkText("Preferências")).Click();
    Assert.That(driver.FindElement(By.Name("language")).Text, Is.EqualTo("auto\\\\nafrikaans\\\\namharic\\\\narabic\\\\narabicegyptianspoken\\\\nbelarusian_tarask\\\\nbreton\\\\nbulgarian\\\\ncatalan\\\\nchinese_simplified\\\\nchinese_traditional\\\\ncroatian\\\\nczech\\\\ndanish\\\\ndutch\\\\nenglish\\\\nestonian\\\\nfinnish\\\\nfrench\\\\ngalician\\\\ngerman\\\\ngreek\\\\nhebrew\\\\nhungarian\\\\nicelandic\\\\ninterlingua\\\\nitalian\\\\njapanese\\\\nkorean\\\\nlatvian\\\\nlithuanian\\\\nmacedonian\\\\nnorwegian_bokmal\\\\nnorwegian_nynorsk\\\\noccitan\\\\npolish\\\\nportuguese_brazil\\\\nportuguese_standard\\\\nripoarisch\\\\nromanian\\\\nrussian\\\\nserbian\\\\nserbian_latin\\\\nslovak\\\\nslovene\\\\nspanish\\\\nswissgerman\\\\nswedish\\\\ntagalog\\\\nturkish\\\\nukrainian\\\\nurdu\\\\nvietnamese\\\\nvolapuk"));
    driver.FindElement(By.CssSelector("body > div img")).Click();
  }
}
