// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class CTRelatarCasoTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void cTRelatarCaso() {
    driver.Navigate().GoToUrl("https://mantis-prova.base2.com.br/login_page.php");
    driver.Manage().Window.Size = new System.Drawing.Size(665, 727);
    driver.FindElement(By.Name("username")).Click();
    driver.FindElement(By.Name("username")).SendKeys("tiago.soares");
    driver.FindElement(By.Name("password")).Click();
    driver.FindElement(By.Name("password")).SendKeys("98554211");
    driver.FindElement(By.CssSelector(".button")).Click();
    driver.FindElement(By.LinkText("Relatar Caso")).Click();
    driver.FindElement(By.CssSelector(".button")).Click();
    driver.FindElement(By.Name("category_id")).Click();
    {
      var dropdown = driver.FindElement(By.Name("category_id"));
      dropdown.FindElement(By.XPath("//option[. = '[Todos os Projetos] 7EI2PODHPN']")).Click();
    }
    driver.FindElement(By.CssSelector(".row-1:nth-child(2) option:nth-child(2)")).Click();
    driver.FindElement(By.Name("reproducibility")).Click();
    driver.FindElement(By.CssSelector(".row-2:nth-child(3) option:nth-child(4)")).Click();
    driver.FindElement(By.Name("priority")).Click();
    {
      var dropdown = driver.FindElement(By.Name("priority"));
      dropdown.FindElement(By.XPath("//option[. = 'baixa']")).Click();
    }
    driver.FindElement(By.CssSelector(".row-2:nth-child(5) option:nth-child(2)")).Click();
    driver.FindElement(By.Name("profile_id")).Click();
    {
      var dropdown = driver.FindElement(By.Name("profile_id"));
      dropdown.FindElement(By.XPath("//option[. = 'PlataformaTeste SiSTEMA Windows10']")).Click();
    }
    driver.FindElement(By.CssSelector(".row-1:nth-child(6) option:nth-child(8)")).Click();
    driver.FindElement(By.Name("summary")).Click();
    driver.FindElement(By.Name("summary")).SendKeys("Teste relato de erro ");
    driver.FindElement(By.Name("description")).Click();
    driver.FindElement(By.Name("description")).SendKeys("realizando teste de relato de caso para selenium");
    driver.FindElement(By.Name("steps_to_reproduce")).Click();
    driver.FindElement(By.Name("steps_to_reproduce")).SendKeys("selenium");
    driver.FindElement(By.Name("additional_info")).Click();
    driver.FindElement(By.Name("additional_info")).SendKeys("utilizando o selenium para salvar o relato de casos");
    driver.FindElement(By.CssSelector(".row-2 label")).Click();
    driver.FindElement(By.CssSelector(".button")).Click();
    var elements = driver.FindElements(By.CssSelector(".button"));
    Assert.True(elements.Count > 0);
    Assert.That(driver.FindElement(By.CssSelector("div:nth-child(5)")).Text, Is.EqualTo("Operação realizada com sucesso.\\\\n[ Visualizar Caso Enviado 5836 ] [ Ver Casos ]"));
    var elements = driver.FindElements(By.CssSelector("div:nth-child(5)"));
    Assert.True(elements.Count > 0);
    driver.FindElement(By.LinkText("Sair")).Click();
  }
}
